
export const projectList = [
    {
        id:0,
        name:'Ozan SuperApp',
        title:'Front-end Development',
        date:'2022',
        img:'http://korayaslan.com/portfolio/assets/img/ozan.png',
        link:'http://korayaslan.com/portfolio/assets/img/ozan.png',
    },
    {
        id:1,
        name:'KlampHost',
        title:'Front-end Development',
        date:'2021',
        img:'http://korayaslan.com/portfolio/assets/img/klamp.png',
        link:'http://korayaslan.com/portfolio/assets/img/klamp.png',
    },
    {
        id:2,
        name:'Payfull',
        title:'Front-end Development',
        date:'2020',
        img:'http://korayaslan.com/portfolio/assets/img/payfull.png',
        link:'http://korayaslan.com/portfolio/assets/img/payfull.png',
    },
    {
        id:3,
        name:'Paybull',
        title:'Front-end Development',
        date:'2020',
        img:'http://korayaslan.com/portfolio/assets/img/paybull.png',
        link:'http://korayaslan.com/portfolio/assets/img/paybull.png',
    },
    {
        id:4,
        name:'Besiktas Aci',
        title:'Front-end Development',
        date:'2020',
        img:'http://korayaslan.com/portfolio/assets/img/aci.png',
        link:'http://korayaslan.com/portfolio/assets/img/aci.png',
    },
    {
        id:5,
        name:'TetiMall',
        title:'Front-end Development',
        date:'2020',
        img:'http://korayaslan.com/portfolio/assets/img/teti.png',
        link:'http://korayaslan.com/portfolio/assets/img/teti.png',
    },
    {
        id:6,
        name:'MagentoTR',
        title:'Front-end Development',
        date:'2019',
        img:'http://korayaslan.com/portfolio/assets/img/magento.png',
        link:'http://korayaslan.com/portfolio/assets/img/magento.png',
    },
    {
        id:7,
        name:'Heeybe',
        title:'Front-end Development',
        date:'2019',
        img:'http://korayaslan.com/portfolio/assets/img/heeybe.png',
        link:'http://korayaslan.com/portfolio/assets/img/heeybe.png',
    }
]